version: '3'
services:
    node:
        build: ./node
        container_name: node
        ports:
            - 3000:3000
        volumes:
            - ../:/product/public
    compass:
        build: ./compass
        container_name: compass
        volumes:
            - ../:/product/public
